apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stackportal
  name: stackportal
spec:
  ports:
  - name: stackportaldatabase_http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: stackportaldatabase_bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    app: stackportal
  type: ClusterIP
status:
  loadBalancer: {}
